spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/BDT02SD
spring.datasource.username=62347
spring.datasource.password=WORKT02SD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


mqtt.broker=tcp://localhost:1883
mqtt.topic=sdist/metrics
mqtt.clientId=server-subscriber-62347
mqtt.username=62347
mqtt.password=WORKT02SD
